USE company;
GO

/*
Combined Stored Procedures Setup

Run this file first, then solve stored_procedures_combined_workbook.sql.

This setup creates compact practice tables for the combined stored procedure
transcripts: banking accounts, transactions, products, branches, school
enrollments, and an error log table for TRY/CATCH practice.
*/

IF OBJECT_ID('dbo.SP_TXN_MASTER', 'U') IS NOT NULL DROP TABLE dbo.SP_TXN_MASTER;
IF OBJECT_ID('dbo.SP_ACCOUNT_MASTER', 'U') IS NOT NULL DROP TABLE dbo.SP_ACCOUNT_MASTER;
IF OBJECT_ID('dbo.SP_PRODUCT_MASTER', 'U') IS NOT NULL DROP TABLE dbo.SP_PRODUCT_MASTER;
IF OBJECT_ID('dbo.SP_BRANCH_MASTER', 'U') IS NOT NULL DROP TABLE dbo.SP_BRANCH_MASTER;
IF OBJECT_ID('dbo.SP_ENROLLMENT_MASTER', 'U') IS NOT NULL DROP TABLE dbo.SP_ENROLLMENT_MASTER;
IF OBJECT_ID('dbo.SP_STUDENT_MASTER', 'U') IS NOT NULL DROP TABLE dbo.SP_STUDENT_MASTER;
IF OBJECT_ID('dbo.SP_COURSE_MASTER', 'U') IS NOT NULL DROP TABLE dbo.SP_COURSE_MASTER;
IF OBJECT_ID('dbo.SP_SQL_LOGS', 'U') IS NOT NULL DROP TABLE dbo.SP_SQL_LOGS;
GO

CREATE TABLE dbo.SP_BRANCH_MASTER
(
    BRID CHAR(3) PRIMARY KEY,
    BRANCH_NAME VARCHAR(40) NOT NULL,
    CITY VARCHAR(30) NOT NULL
);

CREATE TABLE dbo.SP_PRODUCT_MASTER
(
    PID CHAR(2) PRIMARY KEY,
    PRODUCT_NAME VARCHAR(40) NOT NULL,
    MIN_BAL MONEY NOT NULL
);

CREATE TABLE dbo.SP_ACCOUNT_MASTER
(
    ACID INT PRIMARY KEY,
    NAME VARCHAR(40) NOT NULL,
    BRID CHAR(3) NOT NULL REFERENCES dbo.SP_BRANCH_MASTER(BRID),
    PID CHAR(2) NOT NULL REFERENCES dbo.SP_PRODUCT_MASTER(PID),
    DOO DATE NOT NULL,
    CBAL MONEY NOT NULL,
    UBAL MONEY NOT NULL,
    STATUS CHAR(1) NOT NULL
);

CREATE TABLE dbo.SP_TXN_MASTER
(
    TXN_ID INT IDENTITY(1,1) PRIMARY KEY,
    ACID INT NOT NULL REFERENCES dbo.SP_ACCOUNT_MASTER(ACID),
    DOT DATE NOT NULL,
    TXN_TYPE CHAR(3) NOT NULL,
    CHQ_NO INT NULL,
    TXN_AMOUNT MONEY NOT NULL,
    BRID CHAR(3) NOT NULL REFERENCES dbo.SP_BRANCH_MASTER(BRID),
    UID INT NOT NULL,
    CONSTRAINT CK_SP_TXN_TYPE CHECK (TXN_TYPE IN ('CD', 'CW', 'CQD'))
);

CREATE TABLE dbo.SP_STUDENT_MASTER
(
    STUDENT_ID INT PRIMARY KEY,
    STUDENT_NAME VARCHAR(40) NOT NULL,
    ORIGIN VARCHAR(20) NOT NULL,
    STUDENT_TYPE VARCHAR(20) NOT NULL
);

CREATE TABLE dbo.SP_COURSE_MASTER
(
    COURSE_ID INT PRIMARY KEY,
    COURSE_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE dbo.SP_ENROLLMENT_MASTER
(
    ENROLLMENT_ID INT IDENTITY(1,1) PRIMARY KEY,
    STUDENT_ID INT NOT NULL REFERENCES dbo.SP_STUDENT_MASTER(STUDENT_ID),
    COURSE_ID INT NOT NULL REFERENCES dbo.SP_COURSE_MASTER(COURSE_ID),
    DOE DATE NOT NULL,
    FEE_PAID CHAR(1) NOT NULL,
    GRADE CHAR(1) NULL
);

CREATE TABLE dbo.SP_SQL_LOGS
(
    LOG_ID INT IDENTITY(1,1) PRIMARY KEY,
    ERROR_LINE INT NULL,
    ERROR_MESSAGE VARCHAR(MAX) NULL,
    ERROR_NUMBER INT NULL,
    ERROR_PROCEDURE VARCHAR(128) NULL,
    ERROR_DATE_TIME DATETIME NOT NULL DEFAULT GETDATE(),
    ERROR_SEVERITY INT NULL,
    ERROR_STATE INT NULL
);
GO

INSERT INTO dbo.SP_BRANCH_MASTER VALUES
('BR1', 'Hyderabad Main', 'Hyderabad'),
('BR2', 'Bengaluru Central', 'Bengaluru'),
('BR3', 'Chennai South', 'Chennai'),
('BR4', 'Mumbai West', 'Mumbai');

INSERT INTO dbo.SP_PRODUCT_MASTER VALUES
('SB', 'Savings Bank', 1000),
('CA', 'Current Account', 5000),
('LN', 'Loan Account', 0);

INSERT INTO dbo.SP_ACCOUNT_MASTER VALUES
(101, 'Billion Rao', 'BR1', 'SB', '2021-01-10', 15000, 15000, 'A'),
(102, 'Simrit Kaur', 'BR2', 'SB', '2021-02-15', 22000, 22000, 'A'),
(103, 'Ravi Kumar', 'BR3', 'CA', '2021-03-20', 8000, 8000, 'A'),
(104, 'Anika Shah', 'BR4', 'SB', '2021-04-05', 500, 500, 'A'),
(105, 'John Mathew', 'BR1', 'CA', '2021-05-12', 35000, 35000, 'A');

INSERT INTO dbo.SP_TXN_MASTER (ACID, DOT, TXN_TYPE, CHQ_NO, TXN_AMOUNT, BRID, UID) VALUES
(101, DATEADD(MONTH, -1, DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()), 3)), 'CD', NULL, 5000, 'BR1', 1),
(101, DATEADD(MONTH, -1, DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()), 8)), 'CW', NULL, 2000, 'BR1', 1),
(101, DATEADD(MONTH, -1, DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()), 14)), 'CQD', 7751, 3000, 'BR2', 2),
(101, DATEADD(MONTH, -1, DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()), 22)), 'CD', NULL, 7000, 'BR1', 1),
(102, DATEADD(MONTH, -1, DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()), 4)), 'CD', NULL, 9000, 'BR2', 2),
(102, DATEADD(MONTH, -1, DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()), 16)), 'CW', NULL, 4500, 'BR2', 2),
(103, DATEADD(MONTH, -1, DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()), 11)), 'CW', NULL, 6000, 'BR3', 3),
(104, DATEADD(MONTH, -1, DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()), 9)), 'CW', NULL, 800, 'BR4', 4),
(105, DATEADD(DAY, -7, CAST(GETDATE() AS DATE)), 'CD', NULL, 10000, 'BR1', 1),
(105, DATEADD(DAY, -3, CAST(GETDATE() AS DATE)), 'CW', NULL, 2500, 'BR1', 1);

INSERT INTO dbo.SP_STUDENT_MASTER VALUES
(201, 'Simrit Kaur', 'India', 'Online'),
(202, 'Ravina Das', 'India', 'Classroom'),
(203, 'Mark Lee', 'USA', 'Online');

INSERT INTO dbo.SP_COURSE_MASTER VALUES
(301, 'SQL Server'),
(302, 'MSBI'),
(303, 'Power BI'),
(304, 'Azure Data Factory');

INSERT INTO dbo.SP_ENROLLMENT_MASTER (STUDENT_ID, COURSE_ID, DOE, FEE_PAID, GRADE) VALUES
(201, 301, DATEADD(MONTH, -2, CAST(GETDATE() AS DATE)), 'Y', 'A'),
(201, 302, DATEADD(MONTH, -1, CAST(GETDATE() AS DATE)), 'Y', 'B'),
(201, 303, DATEADD(DAY, -5, CAST(GETDATE() AS DATE)), 'N', NULL),
(202, 301, DATEADD(MONTH, -3, CAST(GETDATE() AS DATE)), 'Y', 'A'),
(203, 304, DATEADD(DAY, -20, CAST(GETDATE() AS DATE)), 'Y', 'B');
GO

SELECT 'Stored procedure combined setup completed' AS SETUP_STATUS;
GO
